<?php
/**
 * Checksum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace RMoore\Truenas\Model;
use \RMoore\Truenas\ObjectSerializer;

/**
 * Checksum Class Doc Comment
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Checksum
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_ON = 'ON';

    public const NUMBER_OFF = 'OFF';

    public const NUMBER_FLETCHER2 = 'FLETCHER2';

    public const NUMBER_FLETCHER4 = 'FLETCHER4';

    public const NUMBER_SHA256 = 'SHA256';

    public const NUMBER_SHA512 = 'SHA512';

    public const NUMBER_SKEIN = 'SKEIN';

    public const NUMBER_EDONR = 'EDONR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_ON,
            self::NUMBER_OFF,
            self::NUMBER_FLETCHER2,
            self::NUMBER_FLETCHER4,
            self::NUMBER_SHA256,
            self::NUMBER_SHA512,
            self::NUMBER_SKEIN,
            self::NUMBER_EDONR
        ];
    }
}


