<?php
/**
 * InterfaceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RMoore\Truenas\Test\Api;

use \RMoore\Truenas\Configuration;
use \RMoore\Truenas\ApiException;
use \RMoore\Truenas\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InterfaceApiTest Class Doc Comment
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InterfaceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for interfaceBridgeMembersChoicesPost
     *
     * .
     *
     */
    public function testInterfaceBridgeMembersChoicesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceCheckinGet
     *
     * .
     *
     */
    public function testInterfaceCheckinGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceCheckinWaitingGet
     *
     * .
     *
     */
    public function testInterfaceCheckinWaitingGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceChoicesPost
     *
     * .
     *
     */
    public function testInterfaceChoicesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceCommitPost
     *
     * .
     *
     */
    public function testInterfaceCommitPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceGet
     *
     * .
     *
     */
    public function testInterfaceGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceHasPendingChangesGet
     *
     * .
     *
     */
    public function testInterfaceHasPendingChangesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceIdIdDelete
     *
     * .
     *
     */
    public function testInterfaceIdIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceIdIdGet
     *
     * .
     *
     */
    public function testInterfaceIdIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceIdIdPut
     *
     * .
     *
     */
    public function testInterfaceIdIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceIpInUsePost
     *
     * .
     *
     */
    public function testInterfaceIpInUsePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceLacpduRateChoicesGet
     *
     * .
     *
     */
    public function testInterfaceLacpduRateChoicesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceLagPortsChoicesPost
     *
     * .
     *
     */
    public function testInterfaceLagPortsChoicesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfacePost
     *
     * .
     *
     */
    public function testInterfacePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceRollbackGet
     *
     * .
     *
     */
    public function testInterfaceRollbackGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceServicesRestartedOnSyncGet
     *
     * .
     *
     */
    public function testInterfaceServicesRestartedOnSyncGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceVlanParentInterfaceChoicesGet
     *
     * .
     *
     */
    public function testInterfaceVlanParentInterfaceChoicesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for interfaceXmitHashPolicyChoicesGet
     *
     * .
     *
     */
    public function testInterfaceXmitHashPolicyChoicesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
