<?php
/**
 * SharingWebdavApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RMoore\Truenas\Test\Api;

use \RMoore\Truenas\Configuration;
use \RMoore\Truenas\ApiException;
use \RMoore\Truenas\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SharingWebdavApiTest Class Doc Comment
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SharingWebdavApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sharingWebdavGet
     *
     * .
     *
     */
    public function testSharingWebdavGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sharingWebdavIdIdDelete
     *
     * .
     *
     */
    public function testSharingWebdavIdIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sharingWebdavIdIdGet
     *
     * .
     *
     */
    public function testSharingWebdavIdIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sharingWebdavIdIdPut
     *
     * .
     *
     */
    public function testSharingWebdavIdIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sharingWebdavPost
     *
     * .
     *
     */
    public function testSharingWebdavPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
