<?php
/**
 * SmartTestApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RMoore\Truenas\Test\Api;

use \RMoore\Truenas\Configuration;
use \RMoore\Truenas\ApiException;
use \RMoore\Truenas\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SmartTestApiTest Class Doc Comment
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SmartTestApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for smartTestDiskChoicesPost
     *
     * .
     *
     */
    public function testSmartTestDiskChoicesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestGet
     *
     * .
     *
     */
    public function testSmartTestGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestIdIdDelete
     *
     * .
     *
     */
    public function testSmartTestIdIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestIdIdGet
     *
     * .
     *
     */
    public function testSmartTestIdIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestIdIdPut
     *
     * .
     *
     */
    public function testSmartTestIdIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestManualTestPost
     *
     * .
     *
     */
    public function testSmartTestManualTestPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestPost
     *
     * .
     *
     */
    public function testSmartTestPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for smartTestResultsGet
     *
     * .
     *
     */
    public function testSmartTestResultsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
