<?php
/**
 * SystemApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TrueNAS RESTful API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace RMoore\Truenas\Test\Api;

use \RMoore\Truenas\Configuration;
use \RMoore\Truenas\ApiException;
use \RMoore\Truenas\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SystemApiTest Class Doc Comment
 *
 * @category Class
 * @package  RMoore\Truenas
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SystemApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for systemBootIdGet
     *
     * .
     *
     */
    public function testSystemBootIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemDebugGet
     *
     * .
     *
     */
    public function testSystemDebugGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemEnvironmentGet
     *
     * .
     *
     */
    public function testSystemEnvironmentGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemFeatureEnabledPost
     *
     * .
     *
     */
    public function testSystemFeatureEnabledPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemHostIdGet
     *
     * .
     *
     */
    public function testSystemHostIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemInfoGet
     *
     * .
     *
     */
    public function testSystemInfoGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemIsFreenasGet
     *
     * .
     *
     */
    public function testSystemIsFreenasGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemIsStableGet
     *
     * .
     *
     */
    public function testSystemIsStableGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemLicenseUpdatePost
     *
     * .
     *
     */
    public function testSystemLicenseUpdatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemProductNameGet
     *
     * .
     *
     */
    public function testSystemProductNameGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemProductTypeGet
     *
     * .
     *
     */
    public function testSystemProductTypeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemReadyGet
     *
     * .
     *
     */
    public function testSystemReadyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemRebootPost
     *
     * .
     *
     */
    public function testSystemRebootPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemShutdownPost
     *
     * .
     *
     */
    public function testSystemShutdownPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemStateGet
     *
     * .
     *
     */
    public function testSystemStateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for systemVersionGet
     *
     * .
     *
     */
    public function testSystemVersionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
